In [2]:
import pandas as pd

In [22]:
data = pd.read_csv("data/fire.csv")
df = pd.DataFrame(data)

In [18]:
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight
0,-18.411,145.322,334.8,1.3,1.1,2020-01-01,50,Terra,MODIS,80,6.0NRT,306.2,33.2,D
1,-18.420,145.308,346.6,1.3,1.1,2020-01-01,50,Terra,MODIS,91,6.0NRT,307.7,61.7,D
2,-18.422,145.321,340.9,1.3,1.1,2020-01-01,50,Terra,MODIS,86,6.0NRT,306.6,47.0,D
3,-18.438,145.281,338.1,1.3,1.1,2020-01-01,50,Terra,MODIS,71,6.0NRT,309.2,34.9,D
4,-18.439,145.293,331.3,1.3,1.1,2020-01-01,50,Terra,MODIS,48,6.0NRT,307.5,22.5,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34851,-36.352,149.557,307.2,2.2,1.4,2020-01-30,1540,Aqua,MODIS,57,6.0NRT,291.6,24.1,N
34852,-36.363,149.531,317.3,2.2,1.4,2020-01-30,1540,Aqua,MODIS,92,6.0NRT,290.3,47.0,N
34853,-41.576,147.789,306.2,2.0,1.4,2020-01-30,1545,Aqua,MODIS,65,6.0NRT,290.6,20.7,N
34854,-41.589,147.786,304.0,2.0,1.4,2020-01-30,1545,Aqua,MODIS,39,6.0NRT,290.7,16.9,N
34855,-30.866,121.501,311.0,1.2,1.1,2020-01-30,1720,Aqua,MODIS,82,6.0NRT,289.2,15.1,N

In [23]:
df = df[df["confidence"] >= 90]
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight
1,-18.420,145.308,346.6,1.3,1.1,2020-01-01,50,Terra,MODIS,91,6.0NRT,307.7,61.7,D
8,-14.474,143.581,351.4,1.0,1.0,2020-01-01,50,Terra,MODIS,95,6.0NRT,300.4,55.8,D
15,-21.417,140.841,352.2,1.0,1.0,2020-01-01,50,Terra,MODIS,94,6.0NRT,315.7,38.5,D
17,-21.369,140.702,371.4,1.0,1.0,2020-01-01,50,Terra,MODIS,100,6.0NRT,312.0,97.3,D
18,-21.367,140.692,363.8,1.0,1.0,2020-01-01,50,Terra,MODIS,100,6.0NRT,315.5,71.8,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19280,-35.842,148.856,318.7,1.9,1.4,2020-01-30,1540,Aqua,MODIS,97,6.0NRT,293.1,45.1,N
19281,-35.844,148.878,318.9,1.9,1.4,2020-01-30,1540,Aqua,MODIS,98,6.0NRT,293.8,44.9,N
19284,-35.856,148.846,319.0,1.9,1.4,2020-01-30,1540,Aqua,MODIS,98,6.0NRT,293.0,46.9,N
19286,-36.077,149.486,324.9,2.1,1.4,2020-01-30,1540,Aqua,MODIS,100,6.0NRT,293.3,68.3,N
19287,-36.363,149.531,317.3,2.2,1.4,2020-01-30,1540,Aqua,MODIS,92,6.0NRT,290.3,47.0,N

314.6